version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: openWeatherMapDemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork: